# Generated by Django 4.1.5 on 2023-02-14 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_rename_digital_product_vegetable_alter_product_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
    ]
